### ISSUE TITLE
binomial is output as fraction

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#1]
The MathML looks like this:

```
<mml:mfenced separators="|">
   <mml:mrow>
      <mml:mfrac linethickness="0pt">
         <mml:mrow>
            <mml:mi>n</mml:mi>
         </mml:mrow>
         <mml:mrow>
            <mml:mi>k</mml:mi>
         </mml:mrow>
      </mml:mfrac>
   </mml:mrow>
</mml:mfenced>
```

This MathML markup seems to adhere to the [official recommendation for binomials](https://www.w3.org/TR/REC-MathML/chap3_3.html#sec3.3.2),

We have to recognize `mfenced` with a single `mfrac` with `linethickness="0pt"` and convert it to something else than `\left(\frac{n}{k}\right)`, maybe [`\binom{n}{k}`](http://tex.stackexchange.com/questions/127707/displaying-the-binomial-coefficient-symbol-in-math-mode). 

Here’s some [docx input](https://github.com/transpect/docx2tex/files/101853/test.docx) to test.

**Comment by mkraetke** [comment]
With the latest commit 94f6c4972ec637bbdbd24cf062964a6626457412, `mfenced` which include a mfrac with a linethickness of zero and two `mrow` childs are converted to `\binom{n}{k}.`
