### ISSUE TITLE
Does this work with libxslt?

### ISSUE THREAD

**Issue by jeroen** [transpect/mml2tex#10]
I am trying to write some simple bindings to convert mathml to latex, but I get a ton of parsing errors when applying `mml2tex.xsl` with libxslt.

**Comment by gimsieke** [comment]
No. This code is XSLT 2.0 and libxslt is an XSLT 1.0 processor. You’d have to use Saxon or another XSLT 2 processor.

**Comment by jeroen** [comment]
OK that explains a lot. Thanks.
