### ISSUE TITLE
bevelled fracs

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#12]
As it is configured now, `<mml:mfrac bevelled="true">` will be converted to a normal `\frac`.

Can we just render the two arguments with a slash in between, or does the slash’s size need to be adapted somehow, for example using [xfrac](https://ctan.org/pkg/xfrac)?

**Comment by mkraetke** [comment]
TeX renders just a regular solidus without , so if we want adapted numbers and solidus, we'd need to include xfrac.

**Comment by gimsieke** [comment]
The primary issue has been that in any case a regular `\frac` was created. Now we can either create a macro taken from xfrac around the two arguments, or we could simply output `arg1` `/` `arg2`. I don’t know whether xfrac will cause any issues with complex arguments.

**Comment by mkraetke** [comment]
In docx2tex there is a heuristic that fraction-like characters that simple text fractions such as `1/2` are automatically treated as `\frac{1}{2}`. I think we can safely change this to `\sfrac{1}{2}`. The only downside I see is that we have another `\usepackage` more. In mml2tex we can change this with respect of the value of the `bevelled`-attribute.

**Comment by mkraetke** [comment]
`<mfrac bevelled="true"/>` is now rendered as `\sfrac` rather than `\frac`.

**Comment by mkraetke** [comment]
5aee722596318869d76528c7c59308a41f44513e

**Comment by gimsieke** [comment]
Added xfrac to https://subversion.le-tex.de/common/transpect-adaptions/docx-xml-tex/latex/transpect.cls
