### ISSUE TITLE
Switching \Upgreek to regular Greek tags for rendering using Katex/MathJax

### ISSUE THREAD

**Issue by dasanb** [transpect/mml2tex#14]
Hi, I'm trying to use the mml2tex for a project to convert MathML tags to Tex, mml2tex produces the output in \Upgreek format for the uppercase greek text. which is not supported by katex or mathjax rendering.

**For Example:** 

mml2tex produces, '_\Upgamma'_ for uppercase gamma (Γ), instead of '\Upgamma' it should be _**'\Gamma'**_

Is there any way to achieve this using mml2tex?

There is also a [old issue](https://github.com/transpect/mml2tex/issues/2) similar to this.
 
It will be very helpful ! Thanks!

**Comment by gimsieke** [comment]
How do you invoke it?

**Comment by gimsieke** [comment]
I added an [input file with a Gamma](https://github.com/transpect/mml2tex/blob/master/example/katexify-example.xml) and some documentation in the [README](https://github.com/transpect/mml2tex#user-content-alternative-xslt-only-invocation-for-katex-compatible-output) on how to invoke katexify.xsl.

**Comment by gimsieke** [comment]
The KaTeX map won’t use Upgreek. 

But also if I replace `<mml:mi>A</mml:mi>` with `<mml:mi>Γ</mml:mi>` in example/example.xml and invoke it like this:

```
calabash/calabash.sh -i source=mml2tex/example/example.xml mml2tex/example/test.xpl
```

I get 

```xml
<article xmlns="http://docbook.org/ns/docbook" version="5.0">
  <title>Area enclosed by a circle</title>
  <equation>
    <?mml2tex \Gamma =\pi r^{2}?>
  </equation>
</article>
```

which I find a bit surprising because xsl/mml2tex.xsl contains `<xsl:param name="use-upgreek-map" as="xs:boolean" select="true()"/>`. 

If you invoke xsl/mml2tex.xsl directly, you might need to pass the parameter `use-upgreek-map=false`.

**Comment by dasanb** [comment]
Hi, @gimsieke I used the `invoke-mml2tex.xsl` to transform file, as you mentioned above changed it to `use-upgreek-map=false()` and it worked! Thanks for the documentation!

**Comment by gimsieke** [comment]
Just a remark for people who don’t pass XDM values such as `false()` as parameters: When invoking it from the command line where you only can supply string values for parameters, you may supply a value of `false` without parentheses. A string value of `'false'` will be cast to the `xs:boolean` value of `false()`, or it might even be specified as an alternative representation of `false()`.
