### ISSUE TITLE
not working mathml without namespace

### ISSUE THREAD

**Issue by gbala2412** [transpect/mml2tex#15]
This is working fine for MathML with the namespace. But the same not working without namespace.

command --- java -jar saxon9.jar -o out.tex with_namespace.mml /xsl/invoke-mml2tex.xsl

without namespace
-----------------
```
input: <math display="block"><mi>a</mi></math>
output: <?xml version="1.0" encoding="UTF-8"?><math display="block"><mi>a</mi></math>
```

with namespace
--------------
```
input: <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" display="block"><mml:mi>a</mml:mi></mml:math>
output: <?xml version="1.0" encoding="UTF-8"?><?mml2tex a?>
```

**Comment by gimsieke** [comment]
We don’t consider this as a bug,  and we are unlikely to do something about it.

**Comment by mkraetke** [comment]
Considering namespaces, please refer to the [MathML spec](https://www.w3.org/TR/MathML3/chapter2.html#interf.namespace).

**Comment by gbala2412** [comment]
Thanks for the reply.  I forgot to include the namespace declaration `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mi>a</mi></math>`. Now it's working.
