### ISSUE TITLE
Error: text mode for log \text{\log}

### ISSUE THREAD

**Issue by gbala2412** [transpect/mml2tex#16]
output:
u_{N}=\text{\log }(r) \left(C_{7}-\frac{1}{4} G r C_{5} r^{2}\right)+C_{8}+\frac{1}{4} G r C_{5} r^{2}-\frac{1}{4} G r C_{6} r^{2}+\frac{1}{64} G r \gamma _{2} r^{4}-\frac{p_{s}r^{2}}{4},

input:
`<math xmlns="http://www.w3.org/1998/Math/MathML" altimg="si97.svg" alttext="Equation 13b."><msub><mi>u</mi><mi>N</mi></msub><mo linebreak="goodbreak" color="green">=</mo><mtext >log</mtext><mrow><mrow><mo stretchy="true">(</mo><mi>r</mi><mo stretchy="true">)</mo></mrow></mrow><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mrow><mrow><mo stretchy="true">(</mo><mrow><msub><mi>C</mi><mn>7</mn></msub><mo linebreak="badbreak" color="orange">−</mo><mfrac><mn>1</mn><mn>4</mn></mfrac><mo linebreak="badbreak" linebreakmultchar="·" color="orange">⁢</mo><mi>G</mi><mo linebreak="nobreak">⁢</mo><mi>r</mi><mo linebreak="nobreak">⁢</mo><msub><mi>C</mi><mn>5</mn></msub><mo linebreak="badbreak" linebreakmultchar="·" color="orange">⁢</mo><msup><mi>r</mi><mn>2</mn></msup></mrow><mo stretchy="true">)</mo></mrow></mrow><mo linebreak="goodbreak" color="green">+</mo><msub><mi>C</mi><mn>8</mn></msub><mo linebreak="goodbreak" color="green">+</mo><mfrac><mn>1</mn><mn>4</mn></mfrac><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>G</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>r</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msub><mi>C</mi><mn>5</mn></msub><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msup><mi>r</mi><mn>2</mn></msup><mo linebreak="goodbreak" color="green" >−</mo><mfrac><mn>1</mn><mn>4</mn></mfrac><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>G</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>r</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msub><mi>C</mi><mn>6</mn></msub><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msup><mi>r</mi><mn>2</mn></msup><mo linebreak="goodbreak" color="green">+</mo><mfrac><mn>1</mn><mn>64</mn></mfrac><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>G</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><mi>r</mi><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msub><mi>γ</mi><mn>2</mn></msub><mo linebreak="goodbreak" linebreakmultchar="·" color="green">⁢</mo><msup><mi>r</mi><mn>4</mn></msup><mo linebreak="goodbreak" color="green">−</mo><mfrac><mrow><msub><mi>p</mi><mi>s</mi></msub><msup><mi>r</mi><mn>2</mn></msup></mrow><mn>4</mn></mfrac><mo>,</mo></math>
`

**Comment by mkraetke** [comment]
Function names like log, sin, cos etc. should be wrapped in a `mi` rather than `mtext`. If you get problematic data frequently, you should consider to use [mml-normalize](https://github.com/transpect/mml-normalize) as a MathML preprocessing. mml-normalize contains a set of heuristic patterns to improve the quality of the markup.

**Comment by gbala2412** [comment]
Thanks for the reply.
