### ISSUE TITLE
mmultiscript error

### ISSUE THREAD

**Issue by gbala2412** [transpect/mml2tex#17]
While converting the following MathML I got some errors.

Input: 
`<math xmlns="http://www.w3.org/1998/Math/MathML">
<mmultiscripts>
	<mn>G</mn> 
	<mi>i</mi> 
	<none/>
	<mi>k</mi> 
	<mi>l</mi> 
	<mprescripts />
	<none/>
	<mi>a</mi> 
	<mi>b</mi> 
	<mi>c</mi> 
</mmultiscripts>
</math>`

Error: 
 Recoverable error 
  XTRE0540: Ambiguous rule match for /math/text()[1]
Matches both "*[not(local-name() = ('mi', 'mo', 'mn', 'ms',
  'mtext'))]/text()[not(normalize-space(.))]" on line 735 of
  file:/home/mml2tex-master/xsl/mml2tex.xsl
and "text()[matches(., concat('^(', $whitespace-regex, ')*$'))]" on line 725 of
  file:/home/mml2tex-master/xsl/mml2tex.xsl
Recoverable error 
  XTRE0540: Ambiguous rule match for /math/text()[2]
Matches both "*[not(local-name() = ('mi', 'mo', 'mn', 'ms',
  'mtext'))]/text()[not(normalize-space(.))]" on line 735 of
  file:/home/mml2tex-master/xsl/mml2tex.xsl
and "text()[matches(., concat('^(', $whitespace-regex, ')*$'))]" on line 725 of
  file:/home/mml2tex-master/xsl/mml2tex.xsl

**Comment by mkraetke** [comment]
When I take your input and transform it with mml2tex like this…
```
$ saxon -s:test.mml.xml -xsl:mml2tex/xsl/test-mml.xsl -it:main
```
…I got this output (without any warnings):

```tex
\tensor*[_{}^{a}_{b}^{c}]{G}{_{i}^{}_{k}^{l}}
```
If you use it together with the `tensor` package, this should be rendered like this:

<img width="226" alt="tensor" src="https://user-images.githubusercontent.com/983392/145841641-7a635b64-795d-489b-9a5a-a85003231f14.png">

How do you invoked mml2tex?

**Comment by gbala2412** [comment]
I've tried in latest code.

command:
java -jar saxon9.jar -o out.tex test.mml invoke-mml2tex.xsl

output:
`<?xml version="1.0" encoding="UTF-8"?><?mml2tex \tensor*[_{}^{}_{}^{a}_{}^{}_{}^{b}_{}^{}_{}^{c}_{}^{}_{}]{G}{_{G}^{}_{}^{}_{i}^{}_{}^{}_{}^{}_{k}^{}_{}^{}_{l}^{}_{}^{}}?>`

Error:
Recoverable error 
  XTRE0540: Ambiguous rule match for /math/text()[1]
Matches both "*[not(local-name() = ('mi', 'mo', 'mn', 'ms',
  'mtext'))]/text()[not(normalize-space(.))]" on line 758 of
  file:/home/Downloads/mml2tex-master/xsl/mml2tex.xsl
and "text()[matches(., concat('^(', $whitespace-regex, ')*$'))]" on line 748 of
  file:/home/Downloads/mml2tex-master/xsl/mml2tex.xsl
Recoverable error 
  XTRE0540: Ambiguous rule match for /math/text()[2]
Matches both "*[not(local-name() = ('mi', 'mo', 'mn', 'ms',
  'mtext'))]/text()[not(normalize-space(.))]" on line 758 of
  file:/home/Downloads/mml2tex-master/xsl/mml2tex.xsl
and "text()[matches(., concat('^(', $whitespace-regex, ')*$'))]" on line 748 of
  file:/home/Downloads/mml2tex-master/xsl/mml2tex.xsl

**Comment by mkraetke** [comment]
The whitespace nodes caused the issue. Generally, we use `invoke-mml2tex.xsl` rather for internal use with XProc than command line. Therefore `test-mml.xsl` should be more reliable:

```
$ saxon -s:input.mml.xml -o:output.tex -xsl:mml2tex/xsl/test-mml.xsl -it:main
```
However, the issue should be fixed with the referenced commit.
