### ISSUE TITLE
Convert mathml "<mtext>Ω</mtext>"

### ISSUE THREAD

**Issue by tuyuan2012** [transpect/mml2tex#18]
I use the latest code to convert `"<math xmlns="http://www.w3.org/1998/Math/MathML"><mtext>Ω</mtext></math>"` to latex. The result is `${\Upomega}$`. There are tow `$` which are redundant . I think the result should be \Upomega. The result is \Upomega by  using the previous code.
Thanks.

**Comment by mkraetke** [comment]
There are two stylesheets to invoke mml2tex. `xsl/invoke-mml2tex.xsl` is designed to process MathML in an XML file and include the resulting TeX code it in `mml2tex` processing instructions. The other is `xsl/test-mml.xsl` to convert individual MathML files.

```
$ saxon -xsl:mml2tex/xsl/test-mml.xsl -s:mml2tex/example/Omega.mml.xml -it:main
=> \Upomega
```

You can also have a look into the XSLT files and create your own XSLT which imports mml2tex as library.
