### ISSUE TITLE
Static error

### ISSUE THREAD

**Issue by emrekocyatagi** [transpect/mml2tex#19]
When i run the example (java -jar saxon9he.jar -s:example.xml -xsl:mml2tex/xsl/invoke-mml2tex.xsl) i get these errors

Static error at html on line 1 column 7 of colors.xsl:
  XTSE0150: The supplied file does not appear to be a stylesheet
Static error at xsl:import on line 10 column 35 of invoke-mml2tex.xsl:
  XTSE0165: Reported 1 error in imported stylesheet module
Errors were reported during stylesheet compilation

Is there something i am missing?
And someone  could please explain me simply how i can get tex from mathml? Because i do not understand from README part.

**Comment by gimsieke** [comment]
Probably because since some months ago, we are importing [another XSLT file](https://github.com/transpect/mml2tex/blob/master/xsl/mml2tex.xsl#L16) by its canonical URI that needs an XML catalog resolver to be configured. We need to update the documentation accordingly.

**Comment by emrekocyatagi** [comment]
Thank you so much for this answer.
I guess if i watch this repo i will get the notifications when you updated.
