### ISSUE TITLE
all Greeks are upright

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#2]
Consider this [docx](https://github.com/transpect/docx2tex/files/101853/test.docx) again.

All the greeks are output as their uppercase variants, such as `\upvarphi` or `\upalpha`. The rendering expectations, however, are more like [this](https://twitter.com/letexml/status/690609749663092740), i.e., italic. I think they are regular `<mi>`s. Single-letter `<mi>`s should be rendered italic by default, no matter whether Greek or Latin.

**Comment by mkraetke** [comment]
With commit d284510021b8dd6f6dd1cfd3e1729a44fd010e20, regular greek characters are used instead of upgreek. Upgreek is still used for text mode.
