### ISSUE TITLE
katexify not working

### ISSUE THREAD

**Issue by ribrdb** [transpect/mml2tex#21]
I can't get the katexify xsl to work.
I've tried Saxon 9 HE, Saxon 11 HE, and SaxonJS and I get the same output with all of them. I can run invoke-mml2tex.xsl. But when I try to run the katexify one I get no latex:

For example,  `npx xslt3 -s:example/katexify-example.xml -xsl:xsl/katexify.xsl` outputs `Γ=πr2` not the expected `\Gamma = \pi r ^{2}`

**Comment by gimsieke** [comment]
The [documentation](https://github.com/transpect/mml2tex#user-content-alternative-xslt-only-invocation-for-katex-compatible-output) states that you need to specify an initial mode (`-im:mathml2tex`).
