### ISSUE TITLE
typo error 

### ISSUE THREAD

**Issue by gbala2412** [transpect/mml2tex#22]
Check line number 439 on mml2tex.xsl,  "columnspan" typed as "colunnspan".

`<xsl:sequence select="max(for $i in $mtable/mtr 
                              return xs:integer(sum($i/mtd/@colunnspan)) + count(($i/mtd[empty(@colunnspan)], $i//malignmark))
                             )"/>`

**Comment by gimsieke** [comment]
Yes, you’re right. Thanks for spotting this. This must have had detrimental effects on `mtable`s. 😊 
Do you think we need to create and publish a new docx2tex package quite soon?
I wonder why no one reported an issue with this before. Maybe `mtable`s aren’t that common.

**Comment by gimsieke** [comment]
Ah, `@columnspan` support was declared “experimental“ anyway (see [here](https://github.com/transpect/mml2tex/blame/aebb2cabfda6acbf4ce65880d2653a485970f1c5/xsl/mml2tex.xsl#L439)). As I said, thanks for reporting it nonetheless.

**Comment by gbala2412** [comment]
Thanks for the update. Actually I am try to using your xsl code for mathml to latex conversion.
