### ISSUE TITLE
mtable column alignment issue

### ISSUE THREAD

**Issue by gbala2412** [transpect/mml2tex#23]
Input:
`<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mtable>
    <mtr>
    <mtd columnalign="left"><mn>1</mn></mtd>
    <mtd columnalign="center"><mn>1</mn></mtd>
    <mtd columnalign="right"><mn>1</mn></mtd>
    </mtr>
    </mtable>
</math>`

Output:
`<?xml version="1.0" encoding="UTF-8"?><?mml2tex \begin{array}{lll}
1 & 1 & 1
\end{array} ?>`

Expected Output:
`<?xml version="1.0" encoding="UTF-8"?><?mml2tex \begin{array}{lcr}
1 & 1 & 1
\end{array} ?>`

**Comment by mkraetke** [comment]
Hi @gbala2412,

Thank you for your report. I've fixed the columnalign issue. The output for your MathML document is shown below:

```latex
\begin{array}{lcr}
1 & 1 & 1
\end{array}
```

Kind regards,
Martin

**Comment by gbala2412** [comment]
Thanks for the update. Sorry, instead of the first row of the table consider the first row which contains maximum columns.
otherwise, this fix fails in the following scenario. Correct me If I am wrong.

`<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mtable>
    <mtr>
    <mtd columnalign="left"><mn>1</mn></mtd>
    </mtr>
    <mtr>
    <mtd columnalign="left"><mn>1</mn></mtd>
    <mtd columnalign="center"><mn>1</mn></mtd>
    <mtd columnalign="right"><mn>1</mn></mtd>
    </mtr>
    </mtable>
</math>`

**Comment by mkraetke** [comment]
Thanks for the suggestion. Now we take the row with the most cells for evaluating the column alignment.
