### ISSUE TITLE
min as a unit vs. \min

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#25]
`min` in 
```xml
    <mml:math id="mml_m27">
        <mml:mn>25</mml:mn>
        <mml:mspace width="mediummathspace"/>
        <mml:mtext>m</mml:mtext>
        <mml:mspace width="mediummathspace"/>
        <mml:msup>
            <mml:mtext>min</mml:mtext>
            <mml:mrow>
                <mml:mo>−</mml:mo><mml:mn>1</mml:mn>
            </mml:mrow>
        </mml:msup>
    </mml:math>
```

will be converted to `\min`. The superscript will be put above min:

![grafik](https://user-images.githubusercontent.com/122601/217026458-b4928ca4-9c1a-4493-b248-1fccd68fe913.png)

This is not right when min is interpreted as a physical unit. I propose that we convert `<mtext>min</mtext>` to `\text{min}` when it is contained as the first argument in `msup`, `msubsup`, or `mmultiscripts`.

**Comment by mkraetke** [comment]
Thanks for reporting this issue. Should be fixed with the referenced commit. I've started the tests.
