### ISSUE TITLE
Add support for entity InvisibleTimes (and maybe some others)

### ISSUE THREAD

**Issue by leandromattioli** [transpect/mml2tex#28]
Section 2 of [Units in MathML](https://www.w3.org/TR/mathml-units/) (W3C) has the following snippet:

`
<mrow>
  <mn>35</mn> <mo rspace='thickmathspace'>&InvisibleTimes;</mo>
  <mi mathvariant='normal' class='MathML-Unit'>mm</mi>
</mrow> 
`

This is an official recommendation for typesetting the space between the value and the unit.

When invoking with `saxon`, using the stylesheet `invoke-mml2tex.xsl`, the following error is reported:

`
SXXP0003   Error reported by XML parser: The entity "InvisibleTimes" was referenced, but not declared.
`

Of course we could use other approaches for this space, but the "official way" should be supported.

**Comment by gimsieke** [comment]
We don’t support named entity references at all. We could only process them if we used a DTD that declares them or if we used an HTML parser such as validator.nu. You need to use a numeric entity reference for `&InvisibleTimes;`, that is, `&#x2062;` or `&#8290;`.

**Comment by gimsieke** [comment]
Or to put it differently, it’s your responsibility to either use a DOCTYPE declaration that points to a DTD that declares the entities or to configure a parser such as validator.nu that understands the named entities that HTML5 declares.

**Comment by leandromattioli** [comment]
Indeed, using numeric entity references makes the XSL processor stop warning. 
It should be noted that the rspace attribute, from that minimalist example,  is also ignored. The main XSL emits a proper warning, but, again, I think this should be better documented, along with workarounds. 

Since that other issue is far from this one's title, I'm closing the issue.
