### ISSUE TITLE
xrightarrow is sometimes only provided with an optional argument

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#30]
Consider this input:

```xml filename="mml.xml"
<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML">
  <mml:mover>
    <mml:mi>n</mml:mi>
    <mml:mo stretchy="true">→</mml:mo>
  </mml:mover>
  <mml:mover>
    <mml:msub>
      <mml:mi>q</mml:mi>
      <mml:mrow>
        <mml:mi>r</mml:mi>
        <mml:mo>,</mml:mo>
        <mml:mspace width="0.3em"/>
        <mml:mi>λ</mml:mi>
      </mml:mrow>
    </mml:msub>
    <mml:mo stretchy="true">→</mml:mo>
  </mml:mover>
  <mml:mover accent="true">
    <mml:mi>Δ</mml:mi>
    <mml:mo stretchy="true">→</mml:mo>
  </mml:mover>
</mml:math>
```

Before 3430ae4 it was converted to 

```xml
<?mml2tex \xrightarrow{n}\xrightarrow[{q_{r,\;\lambda }}]{}\vec{\Delta }?>
```

This was wrong because the `n` was placed above the arrow.

(`invocation: saxon -xsl:mml2tex/xsl/invoke-mml2tex.xsl -s:mml.xml`)

The use of `\xrightarrow` for `mml:mover` is questionable anyway. In the KaTeX rendering, for example, the first argument of `mml:mover` won’t be placed on the baseline. The arrow is centered vertically, as seen in this rendering of another formula that contains `mml:mover`:

![grafik](https://github.com/user-attachments/assets/c787d67b-1d01-4047-b6b8-1facf552279f)

MathML code:

```xml filename="mml2.xml"
<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML">
  <mml:mover>
    <mml:mrow>
      <mml:msub>
        <mml:mi>q</mml:mi>
        <mml:mi>n</mml:mi>
      </mml:msub>
    </mml:mrow>
    <mml:mo>→</mml:mo>
  </mml:mover>
  <mml:mo>=</mml:mo>
  <mml:mover>
    <mml:mrow>
      <mml:msub>
        <mml:mi>q</mml:mi>
        <mml:mrow>
          <mml:mi>cd</mml:mi>
          <mml:mo>,</mml:mo>
          <mml:mi>n</mml:mi>
        </mml:mrow>
      </mml:msub>
    </mml:mrow>
    <mml:mo>→</mml:mo>
  </mml:mover>
  <mml:mo>+</mml:mo>
  <mml:mover>
    <mml:mrow>
      <mml:msub>
        <mml:mi>q</mml:mi>
        <mml:mrow>
          <mml:mi>r</mml:mi>
          <mml:mo>,</mml:mo>
          <mml:mi>n</mml:mi>
        </mml:mrow>
      </mml:msub>
    </mml:mrow>
    <mml:mo>→</mml:mo>
  </mml:mover>
</mml:math>
```

But this can be fixed using `accent="true"`, as demonstrated below.

Now for the bug: After 3430ae4, the first MathML snippet will be converted to this PI:

```xml
<?mml2tex \xrightarrow[n]\xrightarrow[{q_{r,\;\lambda }}]{}\vec{\Delta }?>
```

The first `\xrightarrow` only gets an optional argument, `n`, but not an empty curly brace pair for the main argument.

I will probably add `accent="true"` to `mml:mover` in order to make mml2tex generate `\vec` or `\overrightarrow` in all these cases. 

The output of the second example then looks like this:

```xml
<?mml2tex \overrightarrow{q_{n}}=\overrightarrow{q_{\mathrm{cd},n}}+\overrightarrow{q_{r,n}}?>
```

![grafik](https://github.com/user-attachments/assets/3073db46-8557-4f0b-90dc-fa455c4add27)

But the bug that seems to appear in the absence of `accent="true"` if the first argument of `mml:mover` is a simple `mml:mi` needs to be fixed.

**Comment by mkraetke** [comment]
Thank you for the comprehensive issue description. The required argument is now added. As you pointed out, adding `accent="true"` to `mml:mover` will lead to the expected result. However, the handling of arrow expressions growed rather organically than systematically and might be further complicated by certain heuristics.
