### ISSUE TITLE
U+2061 function application survives

### ISSUE THREAD

**Issue by gimsieke** [transpect/mml2tex#4]
Consider [this gist](https://gist.github.com/gimsieke/8dcc9551a429a482c698) and view it in oXygen, for example.

You’ll see that there are U+2061 characters between \sin and \theta. These should be removed during TeX generation.

**Comment by mkraetke** [comment]
I mapped normally-invisible operators with whitespace in revision 4b89ec42cac80fbb1ca968079e5e6115f24176ce
