### ISSUE TITLE
mmultiscript not supported

### ISSUE THREAD

**Issue by darobin** [transpect/mml2tex#7]
Looking at [the code](https://github.com/transpect/mml2tex/blob/master/xsl/mml2tex.xsl#L112) it seems that this style sheet was ported over from another part of transpect that is using the hub format (or something like that). That specific template hasn't been ported, it just uses `<inf>` and `<sup>` instead of generating tex.

(This is not a bug that affects us otherwise I'd offer a PR, but I thought I'd report it anyway!)

**Comment by mkraetke** [comment]
Thank you for your report. It seems that we did not used `<mmultiscripts>` yet, so this issue wasn't noticed earlier. I'll have a look into the code and change this.

**Comment by mkraetke** [comment]
I've decided to implement `<mmultiscripts>` as `\tensor` [here](https://github.com/transpect/mml2tex/blob/master/xsl/mml2tex.xsl#L112-L135). Therefore you'll need the same-named [package](https://www.ctan.org/pkg/tensor). It shouldn't interfere with common math packages and the rendering is more close to the MathML preview.
