### ISSUE TITLE
mfenced is not closed

### ISSUE THREAD

**Issue by flagang** [transpect/mml2tex#8]
at line 319:
`<xsl:when test="not(normalize-space($val))">
      
      </xsl:when>`

it may change to :
`<xsl:when test="not(normalize-space($val))">
       <xsl:text>\</xsl:text>
       <xsl:value-of select="$pos"/>
        <xsl:text>.</xsl:text>
     </xsl:when>`

or it will be wrong because of the lack of \right.

**Comment by mkraetke** [comment]
Thank you for your report. The code snippet above would cause `\right` and `\left` to be set without any brackets. This would raise errors during the LaTeX run. I think it would not make much sense to use opening brackets without closing brackets. Can you please provide me an MathML sample so I can figure out the problem?

**Comment by mkraetke** [comment]
I've resolved this issue with commit 2bba95cb0ce28c1041cf30e58f0a5aaeb2590656. Now `\left.` and `\right.` are inserted for empty attribute values in `@open` and `@close`.
